# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: ogion/firstandonly:latest

    working_directory: /home/seluser/join-tests

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout
      - run: ./gradlew
      - store_test_results:
          path: build/test-results/
      - store_artifacts:
          path: build/reports/allure-report