# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: selenium/standalone-chrome:latest
      #- image: selenium/standalone-chrome-debug:latest
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: /home/

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m

    steps:
      - run: pwd
      - run: ls -lah
      - checkout
      # run tests!
      - run: ./gradlew --stacktrace
      - run: chromedriver --whitelisted-ips=
      - store_test_results:
          path: build/reports/allure-reports